### ISSUE TITLE
Individual Project - Checkpoint 3 ready for review

### ISSUE THREAD

**Issue by Mlor10** [Mlor10/indieProject#10]
@pawaitemadisoncollege - Checkpoint 3 is ready for review

Things I've added since checkpoint 2
- Auth through AWS cognito
- Week 7 classes involved with auth and login
- Logout servlet similar to login but it uses the /logout? endpoint with parameter values for client id and logout_uri, which is the signout url that I set in my user pool in AWS

The db info can be searched with the search bar top right in the navigation bar and I've added a db-diagram since then so my db info can be seen because I'm only showing usernames for users and card name for cards so far. If you search empty, it should pull up every db data. I am going to work on an admin feature once I get the other features set up such as user threads and reports.
Link to the db-diagram for reference to db info
[db-diagram](https://github.com/Mlor10/indieProject/blob/master/DesignDocuments/db-diagram.png)

**Comment by pawaitemadisoncollege** [comment]
Nice job hitting Checkpoint 3 @Mlor10!  I was able to sign up with a new account and view the data. Seem like you have some good momentum here. Nicely done!  

A couple things:

- [ ] Another way to manage signing out is to invalidate the session (there's a method on Session that does this) when a user clicks "logout".  

- [ ] Consider using the jstl import tag rather than the directive: https://github.com/Mlor10/indieProject/blob/65e27fbd13bc228b2cd95021e2daf082a9796a7e/src/main/webapp/results.jsp#L12. I think we covered the import tag in unit 4 of Adv Java.
